/**
 * UNIVERSIDAD DE SAN CARLOS DE GUATEMALA
 * FACULTAD DE INGENIERIA
 * ESCUELA DE CIENCIAS Y SISTEMAS
 * COMPILADORES 1
 * PROYECTO 1
 * Creado el 21 de septiembre 2011, 03:41AM
 */

/*
 * Muestra los errores presentados por el análisis de compilación
 * @(#)ErroresDialog_GUI.java
 * Proyecto1_200819312 application
 * @author David Y. Gonzalez
 */
package gui;
import java.util.*;
import analisis.*;
import javax.swing.table.*;
/**
 *
 * @author davidson
 */
public class ErroresDialog_GUI extends javax.swing.JDialog {
    /**Lista de errores. Se utiliza para dar la opcion de eliminar errores**/
    private LinkedList<XError> listaErrores;
    //En caso de venir null
    private static final String[] title = new String[]{"Tipo", "Descripción", "Token", "Línea", "Columna"};
    private final String[][] cuerpo;
    /** Creates new form ErroresDialog_GUI */
    public ErroresDialog_GUI(java.awt.Frame parent, boolean modal, LinkedList<XError> listaErrores) {
        super(parent, modal);
        this.listaErrores = listaErrores;
        if (listaErrores == null) {
            cuerpo = new String [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            };
            initComponents();
            return;
        }
        int max = listaErrores.size();
        cuerpo = new String [max][5];
        for (int i = 0; i < max; i++){
            XError error = listaErrores.get(i);
            cuerpo[i][0] = error.getTipo();
            cuerpo[i][1] = error.getDescripcion();
            cuerpo[i][2] = error.getToken();
            cuerpo[i][3] = String.valueOf(error.getLinea());
            cuerpo[i][4] = String.valueOf(error.getColumna());
        }
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbBorrarListaErrores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JBadMeth - Descripción Errores");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new DefaultTableModel(cuerpo,title));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 352;
        gridBagConstraints.ipady = 248;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 25);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jbBorrarListaErrores.setText("Limpiar Lista de Errores");
        jbBorrarListaErrores.setToolTipText("");
        jbBorrarListaErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarListaErroresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jbBorrarListaErrores, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBorrarListaErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarListaErroresActionPerformed
        listaErrores.clear();
        jTable1.setModel(new DefaultTableModel(new String [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            }, title));
    }//GEN-LAST:event_jbBorrarListaErroresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBorrarListaErrores;
    // End of variables declaration//GEN-END:variables
}
