/**
 * UNIVERSIDAD DE SAN CARLOS DE GUATEMALA
 * FACULTAD DE INGENIERIA
 * ESCUELA DE CIENCIAS Y SISTEMAS
 * COMPILADORES 1
 * PROYECTO 1
 * Creado el 03 de septiembre 2011, 5:45PM
 */

package gui;
import gameworld.*;
import gameworld.actors.*;
import javax.swing.*;
/*
 * Es el tablero para jugar.
 * @(#)TableroGame_GUI.java
 * Proyecto1_200819312 application
 * @author David Y. Gonzalez
 */
public class TableroGame_GUI extends javax.swing.JFrame {

    /** Creates new form Tablero_GUI */
    public TableroGame_GUI() {
        initComponents();
        addKeyListener(tableroMatriz1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableroMatriz1 = new gameworld.TableroMatriz();
        jtbStartGame = new javax.swing.JToggleButton();
        jcbDrawCuadricula = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfHXImagen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfHXNombre = new javax.swing.JTextField();
        jlHXImagen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfHXDestruir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfHXVida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfAXImagen = new javax.swing.JTextField();
        jlAXImagen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfAXNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfAXDestruir = new javax.swing.JTextField();
        jtfAXDescripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfAXAlcance = new javax.swing.JTextField();
        jtfAXUso = new javax.swing.JTextField();
        jtfHXDescripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JBadMeth - Scene Play");
        setBounds(new java.awt.Rectangle(70, 15, 1200, 720));
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("gui/acercade/Circle_Blue.png")).getImage() );
        setMinimumSize(new java.awt.Dimension(1200, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout tableroMatriz1Layout = new javax.swing.GroupLayout(tableroMatriz1);
        tableroMatriz1.setLayout(tableroMatriz1Layout);
        tableroMatriz1Layout.setHorizontalGroup(
            tableroMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        tableroMatriz1Layout.setVerticalGroup(
            tableroMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jtbStartGame.setText("Iniciar Juego");
        jtbStartGame.setFocusable(false);
        jtbStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbStartGameActionPerformed(evt);
            }
        });

        jcbDrawCuadricula.setText("Dibujar Cuadrícula");
        jcbDrawCuadricula.setFocusable(false);
        jcbDrawCuadricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDrawCuadriculaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Datos Jugador");
        jLabel1.setFocusable(false);
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 23, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("x-imagen");
        jLabel2.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jtfHXImagen.setEditable(false);
        jtfHXImagen.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jtfHXImagen, gridBagConstraints);

        jLabel3.setText("x-nombre");
        jLabel3.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jtfHXNombre.setEditable(false);
        jtfHXNombre.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jtfHXNombre, gridBagConstraints);

        jlHXImagen.setFocusable(false);
        jlHXImagen.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jlHXImagen, gridBagConstraints);

        jLabel4.setText("x-descripción");
        jLabel4.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("x-destruir");
        jLabel5.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 0, 15);
        jPanel1.add(jLabel5, gridBagConstraints);

        jtfHXDestruir.setEditable(false);
        jtfHXDestruir.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 15);
        jPanel1.add(jtfHXDestruir, gridBagConstraints);

        jLabel6.setText("x-vida");
        jLabel6.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 1, 10);
        jPanel1.add(jLabel6, gridBagConstraints);

        jtfHXVida.setBackground(new java.awt.Color(153, 255, 153));
        jtfHXVida.setEditable(false);
        jtfHXVida.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jtfHXVida, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setBackground(new java.awt.Color(102, 204, 255));
        jLabel7.setText("Datos Arma");
        jLabel7.setFocusable(false);
        jLabel7.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("x-imagen");
        jLabel8.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel8, gridBagConstraints);

        jtfAXImagen.setEditable(false);
        jtfAXImagen.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXImagen, gridBagConstraints);

        jlAXImagen.setFocusable(false);
        jlAXImagen.setInheritsPopupMenu(false);
        jlAXImagen.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jlAXImagen, gridBagConstraints);

        jLabel9.setText("x-nombre");
        jLabel9.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel2.add(jLabel9, gridBagConstraints);

        jtfAXNombre.setEditable(false);
        jtfAXNombre.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXNombre, gridBagConstraints);

        jLabel10.setText("x-descripción");
        jLabel10.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel10, gridBagConstraints);

        jLabel11.setText("x-destruir");
        jLabel11.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel11, gridBagConstraints);

        jtfAXDestruir.setEditable(false);
        jtfAXDestruir.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXDestruir, gridBagConstraints);

        jtfAXDescripcion.setEditable(false);
        jtfAXDescripcion.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXDescripcion, gridBagConstraints);

        jLabel12.setText("x-alcance");
        jLabel12.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel12, gridBagConstraints);

        jLabel13.setText("x-uso");
        jLabel13.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jLabel13, gridBagConstraints);

        jtfAXAlcance.setEditable(false);
        jtfAXAlcance.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXAlcance, gridBagConstraints);

        jtfAXUso.setBackground(new java.awt.Color(153, 255, 153));
        jtfAXUso.setEditable(false);
        jtfAXUso.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel2.add(jtfAXUso, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        jtfHXDescripcion.setEditable(false);
        jtfHXDescripcion.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 1, 1, 10);
        jPanel1.add(jtfHXDescripcion, gridBagConstraints);

        jLabel14.setBackground(new java.awt.Color(153, 255, 153));
        jLabel14.setText("<html>Movimiento: Izquierda <br>y Derecha. <br> Saltar: Arriba<br> Disparar: S</html>");
        jLabel14.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtbStartGame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                        .addComponent(jcbDrawCuadricula)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(tableroMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableroMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbDrawCuadricula)
                            .addComponent(jtbStartGame))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbStartGameActionPerformed
        if (tableroMatriz1.isGameEnded()){ 
            jtbStartGame.setText("Juego ha terminado");
            return;
        }
        if (jtbStartGame.isSelected()){
            if (!tableroMatriz1.gamePlaying()){
                jtbStartGame.setText("Pausar Juego");
                requestFocus();
                tableroMatriz1.game();
            } else {
                System.out.println("inconsistencia en isSelected=true;");
            }
        } else {
            if (tableroMatriz1.gamePlaying()){
                jtbStartGame.setText("Continuar Juego");
                tableroMatriz1.gamePause();
            } else {
                System.out.println("inconsistencia en isSelected=false;");
            }
        }
    }//GEN-LAST:event_jtbStartGameActionPerformed

    private void jcbDrawCuadriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDrawCuadriculaActionPerformed
        tableroMatriz1.setDrawCuadricula(jcbDrawCuadricula.isSelected());
    }//GEN-LAST:event_jcbDrawCuadriculaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //pausar el juego
        jtbStartGame.setSelected(false);
        jtbStartGame.setText("Continuar Juego");
        tableroMatriz1.gamePause();
    }//GEN-LAST:event_formWindowClosing

    public void displayHeroe(){
        Heroe h = tableroMatriz1.getHeroe();
        jtfHXImagen.setText(h.getX_imagen());
        jlHXImagen.setIcon(new ImageIcon(tableroMatriz1.imageCache.getSprite(h.getX_imagen())));
        jtfHXNombre.setText(h.getX_nombre());
        jtfHXDescripcion.setText(h.getX_descripcion());
        jtfHXDestruir.setText(String.valueOf(h.getX_destruir()));
        setXVida(h.getX_vida());
        displayArma(h.getWeapon());
    }
    public void displayArma(Arma a){
        if (a == null) return;
        jtfAXImagen.setText(a.getX_imagen());
        jlAXImagen.setIcon(new ImageIcon(tableroMatriz1.imageCache.getSprite(a.getX_imagen())));
        jtfAXNombre.setText(a.getX_nombre());
        jtfAXDescripcion.setText(a.getX_descripcion());
        jtfAXDestruir.setText(String.valueOf(a.getX_destruir()));
        jtfAXAlcance.setText(String.valueOf(a.getX_alcance()));
        setXUso(a.getX_uso());
    }
    /**
     * Muestra la cantidad de vida del heroe
     * @param xvida Numero de la vida
     **/
    public void setXVida(int xvida){
        jtfHXVida.setText(String.valueOf(xvida));
    }
    /**
     * Muestra la cantidad de uso de una arma
     * @param xuso Numero del uso
     **/
    public void setXUso(int xuso){
        jtfAXUso.setText(String.valueOf(xuso));
    }
    /**limpia las casillas del heroe y del arma**/
    public void clearDisplayHeroe(){
        jtfHXImagen.setText("");
        jlHXImagen.setIcon(null);
        jtfHXNombre.setText("");
        jtfHXDescripcion.setText("");
        setXVida(0);
        jtfHXDestruir.setText("0");
        clearDisplayArma();
    }
    /**limpia las casillas del arma**/
    public void clearDisplayArma(){
        jtfAXImagen.setText("");
        jlAXImagen.setIcon(null);
        jtfAXNombre.setText("");
        jtfAXDescripcion.setText("");
        jtfAXDestruir.setText("0");
        jtfAXAlcance.setText("0");
        setXUso(0);
    }
    /**
     * Devuelve la el tablero.
     * Utilizado por el analizador sintactico ParserScene
     * @return El tablero matriz
     **/
    public TableroMatriz getTableroMatriz(){
            return tableroMatriz1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcbDrawCuadricula;
    private javax.swing.JLabel jlAXImagen;
    private javax.swing.JLabel jlHXImagen;
    private javax.swing.JToggleButton jtbStartGame;
    private javax.swing.JTextField jtfAXAlcance;
    private javax.swing.JTextField jtfAXDescripcion;
    private javax.swing.JTextField jtfAXDestruir;
    private javax.swing.JTextField jtfAXImagen;
    private javax.swing.JTextField jtfAXNombre;
    private javax.swing.JTextField jtfAXUso;
    private javax.swing.JTextField jtfHXDescripcion;
    private javax.swing.JTextField jtfHXDestruir;
    private javax.swing.JTextField jtfHXImagen;
    private javax.swing.JTextField jtfHXNombre;
    private javax.swing.JTextField jtfHXVida;
    private gameworld.TableroMatriz tableroMatriz1;
    // End of variables declaration//GEN-END:variables
}
